# Generated by Django 3.0 on 2019-12-15 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('link', models.URLField(max_length=500)),
                ('experience', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=32)),
                ('time', models.CharField(blank=True, choices=[('BRIEF', 'Brief')], max_length=32)),
                ('focus', models.ManyToManyField(related_name='focus', to='backend.Tags')),
                ('prereqs', models.ManyToManyField(related_name='prereqs', to='backend.Tags')),
                ('topics', models.ManyToManyField(related_name='topics', to='backend.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('experience', models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], max_length=64)),
                ('language', models.CharField(blank=True, choices=[('NONE', 'None'), ('JAVA', 'Java'), ('JS', 'Js'), ('PYTHON', 'Python'), ('HTML/CSS', 'Html/css'), ('C++', 'C++')], max_length=32)),
                ('depth', models.CharField(blank=True, max_length=32)),
                ('timeCommitment', models.CharField(blank=True, max_length=32)),
                ('enrolled', models.ManyToManyField(related_name='enrolled', to='backend.Course')),
                ('interests', models.ManyToManyField(related_name='interests', to='backend.Interests')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='resources',
            field=models.ManyToManyField(related_name='courses', to='backend.Resource'),
        ),
    ]
