# Generated by Django 3.0 on 2019-12-15 02:35

import backend.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='experience',
            field=models.CharField(choices=[(backend.enums.Experience['beginner'], 0), (backend.enums.Experience['intermediate'], 1), (backend.enums.Experience['pro'], 2)], default=None, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='time',
            field=models.CharField(choices=[(backend.enums.TimeToComplete['brief'], 0), (backend.enums.TimeToComplete['lengthy'], 1)], default=None, max_length=32),
            preserve_default=False,
        ),
    ]
