# Generated by Django 3.0 on 2019-12-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='experience',
            field=models.CharField(blank=True, choices=[('beginner', 'BEGINNER')], max_length=32),
        ),
        migrations.AddField(
            model_name='resource',
            name='time',
            field=models.CharField(blank=True, choices=[('brief', 'BRIEF')], max_length=32),
        ),
    ]
