# Generated by Django 3.0 on 2019-12-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20191215_0629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
