# Generated by Django 3.0 on 2019-12-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191215_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='depth',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('JAVA', 'Java'), ('JS', 'Js'), ('PYTHON', 'Python'), ('HTML/CSS', 'Html/css'), ('C++', 'C++')], max_length=32),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timeCommitment',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
