# Generated by Django 3.0 on 2019-12-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='tags',
        ),
        migrations.AddField(
            model_name='resource',
            name='focus',
            field=models.ManyToManyField(related_name='focus', to='backend.Tags'),
        ),
        migrations.AddField(
            model_name='resource',
            name='prereqs',
            field=models.ManyToManyField(related_name='prereqs', to='backend.Tags'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topics',
            field=models.ManyToManyField(related_name='topics', to='backend.Tags'),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
