name: learnify
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  http: ^0.12.0+2
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
     - family: Rubik
       fonts:
         - asset: assets/fonts/Rubik-Medium.ttf

